// quotes.ts
export const quotes = [
    "The best investment you can make is in yourself. - Warren Buffett",
    "The stock market is a device for transferring money from the impatient to the patient. - Warren Buffett",
    "Compound interest is the eighth wonder of the world. He who understands it, earns it … he who doesn't … pays it. - Albert Einstein (attributed)",
    "Rule No.1: Never lose money. Rule No.2: Never forget rule No.1. - Warren Buffett",
    "It's not how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for. - Robert Kiyosaki",
    "Formal education will make you a living; self-education will make you a fortune. - Jim Rohn",
    "Price is what you pay. Value is what you get. - Warren Buffett",
    "Beware of little expenses; a small leak will sink a great ship. - Benjamin Franklin",
    "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas. - Paul Samuelson",
    "The four most dangerous words in investing are: 'This time it's different.' - Sir John Templeton",
    "Financial freedom is available to those who learn about it and work for it. - Robert Kiyosaki",
    "Don’t look for the needle in the haystack. Just buy the haystack! - John Bogle",
    "An investment in knowledge pays the best interest. - Benjamin Franklin",
    "The key to financial freedom and great wealth is a person’s ability to convert earned income into passive income and/or portfolio income. - Robert Kiyosaki",
    "I will tell you how to become rich. Close the doors. Be fearful when others are greedy. Be greedy when others are fearful. - Warren Buffett",
    "The biggest risk is not taking any risk... In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
    "The goal isn’t more money. The goal is living life on your terms. - Chris Brogan",
    "Money is a tool. Used properly, it makes something beautiful; used wrong, it makes a mess. - Bradley Vinson",
    "You must gain control over your money or the lack of it will forever control you. - Dave Ramsey",
    "A budget is telling your money where to go instead of wondering where it went. - John C. Maxwell",
    "Never spend your money before you have it. - Thomas Jefferson",
    "Rich people have small TVs and big libraries, and poor people have small libraries and big TVs. - Zig Ziglar",
    "Do not save what is left after spending, but spend what is left after saving. - Warren Buffett",
    "Buy when everyone else is selling and hold until everyone else is buying. That’s not just a catchy slogan. It’s the very essence of successful investing. - J. Paul Getty",
    "The philosophy of the rich and the poor is this: the rich invest their money and spend what is left. The poor spend their money and invest what is left. - Robert Kiyosaki",
  ];